<?xml version="1.0" encoding="utf-8"?><Database Name="Milion" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-HVE17B9\SQLVNEXT;Initial Catalog=Milion;Integrated Security=True" SettingsObjectName="Milioners.Properties.Settings" SettingsPropertyName="MilionConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Questios" Member="Questios">
    <Type Name="Questio">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Questio" Member="Questio1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Answer_1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Answer_2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Answer_3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Answer_4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Delete_Questio" Method="Delete_Questio">
    <Parameter Name="Questio" Parameter="questio" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Update_Questio" Method="Update_Questio">
    <Parameter Name="Questio_old" Parameter="questio_old" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Questio" Parameter="questio" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Answer_1" Parameter="answer_1" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Answer_2" Parameter="answer_2" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Answer_3" Parameter="answer_3" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Answer_4" Parameter="answer_4" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[Save]" Method="Save">
    <Parameter Name="q" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="a1" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="a2" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="a3" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="a4" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
</Database>