//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milioners
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MilionEntities5 : DbContext
    {
        public MilionEntities5()
            : base("name=MilionEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Questio> Questios { get; set; }
    
        public virtual int Delete_Questio(string questio)
        {
            var questioParameter = questio != null ?
                new ObjectParameter("Questio", questio) :
                new ObjectParameter("Questio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Questio", questioParameter);
        }
    
        public virtual int Save(string q, string a1, string a2, string a3, string a4)
        {
            var qParameter = q != null ?
                new ObjectParameter("q", q) :
                new ObjectParameter("q", typeof(string));
    
            var a1Parameter = a1 != null ?
                new ObjectParameter("a1", a1) :
                new ObjectParameter("a1", typeof(string));
    
            var a2Parameter = a2 != null ?
                new ObjectParameter("a2", a2) :
                new ObjectParameter("a2", typeof(string));
    
            var a3Parameter = a3 != null ?
                new ObjectParameter("a3", a3) :
                new ObjectParameter("a3", typeof(string));
    
            var a4Parameter = a4 != null ?
                new ObjectParameter("a4", a4) :
                new ObjectParameter("a4", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Save", qParameter, a1Parameter, a2Parameter, a3Parameter, a4Parameter);
        }
    
        public virtual int Update_Questio(string questio_old, string questio, string answer_1, string answer_2, string answer_3, string answer_4)
        {
            var questio_oldParameter = questio_old != null ?
                new ObjectParameter("Questio_old", questio_old) :
                new ObjectParameter("Questio_old", typeof(string));
    
            var questioParameter = questio != null ?
                new ObjectParameter("Questio", questio) :
                new ObjectParameter("Questio", typeof(string));
    
            var answer_1Parameter = answer_1 != null ?
                new ObjectParameter("Answer_1", answer_1) :
                new ObjectParameter("Answer_1", typeof(string));
    
            var answer_2Parameter = answer_2 != null ?
                new ObjectParameter("Answer_2", answer_2) :
                new ObjectParameter("Answer_2", typeof(string));
    
            var answer_3Parameter = answer_3 != null ?
                new ObjectParameter("Answer_3", answer_3) :
                new ObjectParameter("Answer_3", typeof(string));
    
            var answer_4Parameter = answer_4 != null ?
                new ObjectParameter("Answer_4", answer_4) :
                new ObjectParameter("Answer_4", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Questio", questio_oldParameter, questioParameter, answer_1Parameter, answer_2Parameter, answer_3Parameter, answer_4Parameter);
        }
    }
}
